source 'https://rubygems.org'
gem 'activesupport'
gem 'alsa-rawmidi'
gem 'blankslate'
gem 'did_you_mean'
gem 'edn'
gem 'ffi'
gem 'ffi-coremidi'
gem 'hamster', :git => 'https://github.com/jweather/hamster.git'
gem 'i18n'
gem 'interception'
gem 'kramdown'
gem 'midilib'
gem 'midi-winmm'
gem 'multi_json'
gem 'osc-ruby'
gem 'parslet'
gem 'rouge'
gem 'rubame'
gem 'ruby-beautify', :git => 'https://github.com/jweather/ruby-beautify.git'
gem 'ruby-prof'
gem 'rugged', :git => 'https://github.com/jweather/rugged.git'
gem 'thread_safe'
gem 'unimidi'
gem 'websocket'

