#cmakedefine APP_ROOT "${APP_ROOT}"
#cmakedefine APP_INSTALL_ROOT "${APP_INSTALL_ROOT}"
#cmakedefine SONIC_PI_INSTALL_ROOT "${SONIC_PI_INSTALL_ROOT}"
#cmakedefine QT_OLD_API ${QT_OLD_API}
#cmakedefine RASPBERRY_PI ${RASPBERRY_PI}
#define SONIC_PI_VERSION "${SONIC_PI_VERSION}"

