# Generated by scripts/gen-editor-data.rb from Sonic Pi's docs. Do not edit.
module SonicPi; module Data
VEC_FNS = ["bools", "chord", "chord_degree", "chord_invert", "doubles", "halves", "knit", "line", "midi_notes", "note_range", "octs", "ramp", "range", "ring", "sample_names", "sample_paths", "scale", "spread", "stretch", "tracks", "vector"]
end; end
