#!/bin/bash
set -e # Quit script on error
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
WORKING_DIR="$(pwd)"

cleanup_function() {
    # Restore working directory as it was prior to this script running on exit
    cd "${WORKING_DIR}"
}
trap cleanup_function EXIT

# The GUI compiles against docs/completion headers generated by qt-doc.rb
# (they are gitignored). A missing set, or a leftover from an older
# generator, fails the compile in confusing ways — refuse early instead.
GENERATOR="${SCRIPT_DIR}/server/ruby/bin/qt-doc.rb"
for generated in ruby_help.h completion_argkinds.gen.h \
                 completion_fnopts.gen.h completion_optowners.gen.h; do
    path="${SCRIPT_DIR}/gui/utils/${generated}"
    if [ ! -f "${path}" ] || [ "${GENERATOR}" -nt "${path}" ]; then
        echo "ERROR: generated GUI docs are missing or older than qt-doc.rb"
        echo "       (${generated}). Run the platform prebuild script first"
        echo "       (linux-prebuild.sh / mac-prebuild.sh / pi-prebuild.sh),"
        echo "       or just the *-pre-translations.sh step, to regenerate."
        exit 1
    fi
done

cd "${SCRIPT_DIR}"/build
cmake --build .
