@echo off
set WORKING_DIR=%CD%
set CONFIG=%1
if /I "%CONFIG%" == "" (set CONFIG=Release)
cd %~dp0

REM The GUI compiles against docs/completion headers generated by qt-doc.rb
REM (they are gitignored). A missing set, or a leftover from an older
REM generator, fails the compile in confusing ways - refuse early instead.
if not exist "gui\utils\ruby_help.h" goto stale_docs
if not exist "gui\utils\completion_argkinds.gen.h" goto stale_docs
if not exist "gui\utils\completion_fnopts.gen.h" goto stale_docs
if not exist "gui\utils\completion_optowners.gen.h" goto stale_docs
powershell -NoProfile -Command "exit [int]((Get-Item 'server\ruby\bin\qt-doc.rb').LastWriteTime -gt (Get-Item 'gui\utils\ruby_help.h').LastWriteTime)"
if %ERRORLEVEL% neq 0 goto stale_docs

cd build

REM We need to pass in the make build type here when using Visual Studio 
REM As passing in during the config step isn't honoured
cmake --build . --config %CONFIG%

if %ERRORLEVEL% neq 0 (
    cd %WORKING_DIR%
    exit /b %ERRORLEVEL%
)

cd %WORKING_DIR%
exit /b 0

:stale_docs
echo ERROR: generated GUI docs are missing or older than qt-doc.rb.
echo        Run win-prebuild.bat first to regenerate them.
cd %WORKING_DIR%
exit /b 1
