#!/bin/bash

set -eux

cd $(dirname $0)

cp -f ruby_help.tmpl ruby_help.h
../../server/bin/qt-doc.rb -o ruby_help.h
qmake -o Makefile SonicPi.pro -set RP || qmake-qt4 -o Makefile SonicPi.pro -set RP
set +x
make
