# encoding: utf-8
require_relative "../core"
require 'rake'

require 'rake/testtask'

task :default => :test
Rake::TestTask.new do |t|
  t.libs << 'test'
  t.pattern = 'test/**/test_*.rb'
  t.verbose = true
end

task :coverage do
  ENV['COVERAGE'] = 'true'
  Rake::Task['test'].execute
end
