#!/usr/bin/env ruby
# SPDX-License-Identifier: AGPL-3.0-or-later
# Writes runtime/data/samples.rb: the built-in sample groups as Sonic Pi
# lists them, and — for now — every built-in sample's onsets as found by
# Sonic Pi's aubio_onset (oracle/bin, built by scripts/build-oracle.sh).
#
# The onset table is a stopgap: the runtime is meant to find onsets itself,
# with aubio compiled alongside it, and this table is what that must
# reproduce. Until then, programs that use onset: on built-in samples work.
ROOT = File.expand_path("..", __dir__)
SP = File.join(ROOT, "../../app/server/ruby")
$LOAD_PATH.unshift File.join(SP, "lib")
require File.join(SP, "core")
require "sonicpi/synths/synthinfo"

groups = {}
SonicPi::Synths::BaseInfo.grouped_samples.each { |g, h| groups[g] = { prefix: h[:prefix], samples: h[:samples] } }

onset_bin = File.join(ROOT, "oracle/bin/aubio_onset")
abort "no #{onset_bin}: run scripts/build-oracle.sh" unless File.executable?(onset_bin)
onsets = {}
Dir[File.join(ROOT, "../../etc/samples/*.flac")].sort.each do |path|
  onsets[File.basename(path)] = `"#{onset_bin}" "#{path}"`.split.map(&:to_f)
end

def lit(v)
  case v
  when Hash then "{" + v.map { |k, x| "#{k.is_a?(Symbol) ? k.to_s + ':' : k.inspect + ' =>'} #{lit(x)}" }.join(", ") + "}"
  when Array then "[" + v.map { |x| lit(x) }.join(", ") + "]"
  else v.inspect
  end
end
version = `git -C #{SP} describe --tags`.strip
File.write(File.join(ROOT, "runtime/data/samples.rb"),
  "# Generated by scripts/gen-sample-data.rb from Sonic Pi #{version}. Do not edit.\nmodule SonicPi; module Data\n" +
  "SAMPLE_GROUPS = {\n" + groups.map { |g, h| "  #{g}: #{lit(h)}" }.join(",\n") + "\n}\n" +
  "# onsets in seconds, from aubio_onset (window 1024, hop 512, threshold 0.3, minioi 12 ms)\n" +
  "ONSETS = {\n" + onsets.map { |f, o| "  #{f.inspect} => #{lit(o)}" }.join(",\n") + "\n}\nend; end\n")
puts "#{groups.size} groups, #{onsets.size} samples with onsets -> runtime/data/samples.rb"
