#!/usr/bin/env ruby
# SPDX-License-Identifier: AGPL-3.0-or-later
# Writes runtime/data/synths.rb and runtime/data/theory.rb: for every synth
# and fx native knows, its server name, argument defaults, the args that
# scale with tempo, the slide args and each arg's validation rules; and
# the chord and scale interval tables. Ruby literals, since mruby has no
# JSON; the runtime reads these instead of porting synthinfo, chord and
# scale.
#
# The rules themselves are not written here: lib/sonicpi/validation.rb says whether a value keeps a rule and how
# the rule reads, the server reads that file and the runtime is built from the same one (scripts/build-runtime.sh),
# so a rule cannot mean one thing in the app and another in the browser.
#
# Which Sonic Pi it reads: the checkout this directory is in, or a path given on the command line. The rules
# live in files native has but its last release does not, so the pinned oracle cannot answer for them:
#
#   ruby scripts/gen-synth-data.rb                    # this checkout
#   ruby scripts/gen-synth-data.rb ~/src/sonic-pi     # a checkout of your own
ROOT = File.expand_path("..", __dir__)
NATIVE = File.expand_path(ARGV[0] || File.join(ROOT, "../.."))
SP = File.join(NATIVE, "app/server/ruby")
raise "no Sonic Pi at #{NATIVE} — pass the path to a checkout" unless File.exist?(File.join(SP, "core.rb"))
$LOAD_PATH.unshift File.join(SP, "lib")
require File.join(SP, "core")
require "sonicpi/synths/synthinfo"
require "sonicpi/chord"
require "sonicpi/scale"

# A Hash as a Ruby literal: symbols as keys, plain values.
# a key as it is: a Symbol that is no bare word (chord :'7') stays a Symbol, :"7" =>, not the String "7"
def lit(v, indent = 0)
  pad = "  " * indent
  case v
  when Hash then v.empty? ? "{}" : "{\n" + v.map { |k, x| "#{pad}  #{k.to_s =~ /\A[a-z_][a-zA-Z0-9_]*\z/ ? k.to_s + ':' : k.inspect + ' =>'} #{lit(x, indent + 1)}" }.join(",\n") + "\n#{pad}}"
  when Array then "[" + v.map { |x| lit(x, indent) }.join(", ") + "]"
  when Symbol then v.inspect
  when String then v.inspect
  when Float, Integer, true, false, nil then v.inspect
  else raise "cannot write #{v.inspect} as a literal"
  end
end

# Which opts a synth renames before triggering (its munge_opts), found by
# probing with every alias Sonic Pi uses.
def aliases(info)
  probe = { cutoff: 1, cutoff_slide: 2, cutoff_slide_curve: 3, cutoff_slide_shape: 4 }
  out = begin info.munge_opts(nil, probe.dup) rescue probe end
  res = {}
  probe.each do |k, v|
    next if out.key?(k)
    out.each { |k2, v2| res[k] = k2 if v2 == v }
  end
  res
end

# Whether a synth is given the studio's random stream as it starts (its on_start sets rand_buf: slicer, panslicer
# and wobble toss their probability: coins with it, winwood_lead sets its lfo's phase), found by asking on_start.
RandStudio = Struct.new(:rand_buf_id)
def rand_buf?(info)
  args = {}
  info.on_start(RandStudio.new(:rand_stream), args) rescue nil   # the recorder's wants a buffer: it has no coins
  args[:rand_buf] == :rand_stream
end

def describe(info)
  # From where native's own validate! reads (arg_validations), not from arg_info: the documentation view leaves out
  # the slide opts, and native checks those too — reading the other place would let the browser allow what the
  # app refuses.
  rules = {}
  info.arg_defaults.each_key do |arg|
    vs = info.arg_validations(arg)
    next if vs.empty?
    rs = vs.map { |v| v[3] }.compact
    # a check with no rule behind it is one the runtime cannot keep: the build stops rather than let it pass
    # silently in the browser (validation.rb holds the rules; SynthInfo's v_* build them)
    raise "#{info.synth_name}'s #{arg}: #{vs.length} checks but #{rs.length} rules" if rs.length != vs.length
    rules[arg] = rs
  end
  { scsynth_name: info.scsynth_name, defaults: info.arg_defaults, bpm_scale_args: info.bpm_scale_args,
    slide_args: info.slide_args, rules: rules, kill_delay: (info.kill_delay(info.arg_defaults) rescue nil),
    logical_clock: (info.trigger_with_logical_clock? rescue nil), aliases: aliases(info), midi_args: info.midi_args }
    .merge(rand_buf?(info) ? { rand_buf: true } : {})
end

synths = {}
SonicPi::Synths::SynthInfo.all_synths.each { |n| synths[n] = describe(SonicPi::Synths::SynthInfo.get_info(n)) }
fx = {}
(SonicPi::Synths::SynthInfo.all_fx + [:scope_out]).each do |n|
  info = SonicPi::Synths::SynthInfo.get_info("fx_#{n}") or next
  fx[n] = describe(info)
end
# the sample players are not in all_synths but sample needs them
%w[basic_mono_player basic_stereo_player mono_player stereo_player].each { |n| synths[n.to_sym] = describe(SonicPi::Synths::SynthInfo.get_info(n)) }
version = File.read(File.join(NATIVE, "VERSION")).strip   # the release's (VERSION), not git's: the same on every commit and in a checkout with no tags
dir = File.join(ROOT, "runtime/data")
Dir.mkdir(dir) unless Dir.exist?(dir)
File.write(File.join(dir, "synths.rb"), "# Generated by scripts/gen-synth-data.rb from Sonic Pi #{version}. Do not edit.\nmodule SonicPi; module Data\nSYNTHS = #{lit(synths)}\nFX = #{lit(fx)}\nend; end\n")
File.write(File.join(dir, "theory.rb"), "# Generated by scripts/gen-synth-data.rb from Sonic Pi #{version}. Do not edit.\nmodule SonicPi; module Data\nCHORDS = #{lit(SonicPi::Chord::CHORD_LOOKUP.transform_keys(&:to_sym))}\nSCALES = #{lit(SonicPi::Scale::SCALE.transform_keys(&:to_sym).transform_values(&:to_a))}\n" \
  "CHORD_NAMES = #{SonicPi::Chord::CHORD_NAMES.inspect}\nSYNTH_NAMES = #{SonicPi::Synths::BaseInfo.all_synths.sort.inspect}\nFX_NAMES = #{SonicPi::Synths::BaseInfo.all_fx.sort.inspect}\nend; end\n")
puts "#{synths.size} synths, #{fx.size} fx, #{SonicPi::Chord::CHORD_LOOKUP.size} chords, #{SonicPi::Scale::SCALE.size} scales -> #{dir}"
