#!/bin/bash

#--
# This file is part of Sonic Pi: http://sonic-pi.net
# Full project source: https://github.com/samaaron/sonic-pi
# License: https://github.com/samaaron/sonic-pi/blob/master/LICENSE.md
#
# Copyright 2013, 2014 by Sam Aaron (http://sam.aaron.name).
# All rights reserved.
#
# Permission is granted for use, copying, modification, distribution,
# and distribution of modified versions of this work as long as this
# notice is included.
# ++

# start dbus which is needed by jack
eval $(dbus-launch --auto-syntax)
sleep 2
# start jackd and scsynth
jackd -R -p 32 -d alsa -n 3&
sleep 2
scsynth -u 4556 -m 131072 &
sleep 2
jack_connect SuperCollider:out_1 system:playback_1
jack_connect SuperCollider:out_2 system:playback_2

touch /home/pi/sonic-pi/tmp/running
