#!/bin/bash

# start dbus which is needed by jack
eval $(dbus-launch --auto-syntax)
sleep 2
# start jackd and scsynth
jackd -R -p 32 -d alsa -n 3&
sleep 2
scsynth -u 4556 -m 131072 &
sleep 2
jack_connect SuperCollider:out_1 system:playback_1
jack_connect SuperCollider:out_2 system:playback_2

touch ${HOME}/sonic-pi/tmp/running
