
name: Build

on:
  # Do it on every push or PR on these branches
  push:
#    branches: [ dev, stable ]
  pull_request:
    branches: [ dev, stable ]
  # Do build on demand
  workflow_dispatch:
  
jobs:
  test:
    name: fedora
    runs-on: ubuntu-latest

    steps:
      - name: Setup Podman
        run: |
          sudo apt update
          sudo apt-get -y install podman
          podman pull fedora:latest
      - name: Get source
        uses: actions/checkout@v3
        with:
          path: 'sonic-pi'
      - name: Create container and run tests
        run: |
          echo 'FROM fedora:latest' >> podmanfile
          echo 'RUN dnf -y update' >> podmanfile
          echo 'RUN dnf -y group install "Development Tools"' >> podmanfile
          echo 'RUN dnf -y install alsa-lib-devel alsa-utils cmake elixir erlang erlang-xmerl' >> podmanfile
          echo 'RUN dnf -y install jack-audio-connection-kit-example-clients libX11-devel' >> podmanfile
          echo 'RUN dnf -y install libXft-devel libXext-devel mesa-libGLU-devel ' >> podmanfile
          echo 'RUN dnf -y install ninja-build openssl-devel' >> podmanfile
          echo 'RUN dnf -y install pipewire-jack-audio-connection-kit' >> podmanfile
          echo 'RUN dnf -y install qt5-qtconfiguration-devel qt5-qttools-devel' >> podmanfile
          echo 'RUN dnf -y install qt5-qtsvg-devel rubygem-rexml ruby-devel supercollider' >> podmanfile
          echo 'RUN dnf clean all' >> podmanfile
          echo 'COPY sonic-pi sonic-pi' >> podmanfile
          echo 'WORKDIR /sonic-pi/app' >> podmanfile
          echo 'RUN ./linux-build-all.sh' >> podmanfile
          podman build --tag fedora-latest-testbuild -f ./podmanfile
